-- Create Warehouse
CREATE WAREHOUSE RETAIL_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE RETAIL_ANALYTICS_DB;

CREATE SCHEMA RETAIL_ANALYTICS_DB.RAW;

CREATE SCHEMA RETAIL_ANALYTICS_DB.STAGING;

CREATE SCHEMA RETAIL_ANALYTICS_DB.MART;

CREATE SCHEMA RETAIL_ANALYTICS_DB.REPORTING;

USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA RAW;




USE DATABASE RETAIL_ANALYTICS_DB;

USE SCHEMA RAW;



CREATE STAGE RETAIL_STAGE;



CREATE TABLE CUSTOMERS_RAW (
    CUSTOMER_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    GENDER STRING,
    AGE NUMBER,
    CITY STRING,
    STATE STRING,
    JOIN_DATE DATE,
    CUSTOMER_SEGMENT STRING
);

CREATE TABLE PRODUCTS_RAW (
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    SUB_CATEGORY STRING,
    BRAND STRING,
    UNIT_PRICE NUMBER(10,2)
);

CREATE TABLE STORES_RAW (
    STORE_ID STRING,
    STORE_NAME STRING,
    CITY STRING,
    STATE STRING,
    REGION STRING
);

CREATE TABLE DATES_RAW (
    DATE_KEY NUMBER,
    FULL_DATE DATE,
    DAY NUMBER,
    MONTH NUMBER,
    MONTH_NAME STRING,
    QUARTER NUMBER,
    YEAR NUMBER,
    WEEKDAY STRING,
    WEEK_NUMBER NUMBER,
    IS_WEEKEND BOOLEAN
);

CREATE TABLE SALES_RAW (
    SALES_ID STRING,
    CUSTOMER_ID STRING,
    PRODUCT_ID STRING,
    STORE_ID STRING,
    DATE_KEY NUMBER,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2),
    DISCOUNT NUMBER(10,2),
    SALES_AMOUNT NUMBER(10,2),
    PAYMENT_METHOD STRING
);

USE WAREHOUSE RETAIL_WH;
USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA RAW;

