USE WAREHOUSE RETAIL_WH;
USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA RAW;

-- Verify uploaded files
LIST @RETAIL_STAGE;

-- Create CSV File Format
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL','');

-- Load Customers
COPY INTO CUSTOMERS_RAW
FROM @RETAIL_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

-- Load Products
COPY INTO PRODUCTS_RAW
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

-- Load Stores
COPY INTO STORES_RAW
FROM @RETAIL_STAGE/stores.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

-- Load Dates
COPY INTO DATES_RAW
FROM @RETAIL_STAGE/dates.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

-- Load Sales
COPY INTO SALES_RAW
FROM @RETAIL_STAGE/sales.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

-- Verify Data
SELECT COUNT(*) AS CUSTOMER_COUNT FROM CUSTOMERS_RAW;
SELECT COUNT(*) AS PRODUCT_COUNT FROM PRODUCTS_RAW;
SELECT COUNT(*) AS STORE_COUNT FROM STORES_RAW;
SELECT COUNT(*) AS DATE_COUNT FROM DATES_RAW;
SELECT COUNT(*) AS SALES_COUNT FROM SALES_RAW;

SELECT * FROM CUSTOMERS_RAW LIMIT 10;