USE WAREHOUSE RETAIL_WH;
USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA STAGING;


CREATE OR REPLACE TABLE CUSTOMERS_STG AS
SELECT
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    INITCAP(TRIM(FIRST_NAME)) AS FIRST_NAME,
    INITCAP(TRIM(LAST_NAME)) AS LAST_NAME,
    UPPER(TRIM(GENDER)) AS GENDER,
    AGE,
    INITCAP(TRIM(CITY)) AS CITY,
    UPPER(TRIM(STATE)) AS STATE,
    JOIN_DATE,
    UPPER(TRIM(CUSTOMER_SEGMENT)) AS CUSTOMER_SEGMENT
FROM RETAIL_ANALYTICS_DB.RAW.CUSTOMERS_RAW
WHERE CUSTOMER_ID IS NOT NULL;

SELECT * FROM CUSTOMERS_STG LIMIT 10;

SELECT COUNT(*) FROM CUSTOMERS_STG;

SELECT COUNT(*) FROM RETAIL_ANALYTICS_DB.RAW.CUSTOMERS_RAW;


CREATE OR REPLACE TABLE PRODUCTS_STG AS
SELECT
    TRIM(PRODUCT_ID) AS PRODUCT_ID,
    INITCAP(TRIM(PRODUCT_NAME)) AS PRODUCT_NAME,
    UPPER(TRIM(CATEGORY)) AS CATEGORY,
    UPPER(TRIM(SUB_CATEGORY)) AS SUB_CATEGORY,
    INITCAP(TRIM(BRAND)) AS BRAND,
    ROUND(UNIT_PRICE, 2) AS UNIT_PRICE
FROM RETAIL_ANALYTICS_DB.RAW.PRODUCTS_RAW
WHERE PRODUCT_ID IS NOT NULL;

SELECT COUNT(*) FROM PRODUCTS_STG;

SELECT * FROM PRODUCTS_STG LIMIT 10;


CREATE OR REPLACE TABLE STORES_STG AS
SELECT
    TRIM(STORE_ID) AS STORE_ID,
    INITCAP(TRIM(STORE_NAME)) AS STORE_NAME,
    INITCAP(TRIM(CITY)) AS CITY,
    UPPER(TRIM(STATE)) AS STATE,
    UPPER(TRIM(REGION)) AS REGION
FROM RETAIL_ANALYTICS_DB.RAW.STORES_RAW
WHERE STORE_ID IS NOT NULL;

SELECT COUNT(*) FROM STORES_STG;

SELECT * FROM STORES_STG LIMIT 10;


CREATE OR REPLACE TABLE DATES_STG AS
SELECT
    DATE_KEY,
    FULL_DATE,
    DAY,
    MONTH,
    MONTH_NAME,
    QUARTER,
    YEAR,
    WEEKDAY,
    WEEK_NUMBER,
    IS_WEEKEND
FROM RETAIL_ANALYTICS_DB.RAW.DATES_RAW;

SELECT COUNT(*) FROM DATES_STG;

SELECT * FROM DATES_STG LIMIT 10;

CREATE OR REPLACE TABLE SALES_STG AS
SELECT
    TRIM(SALES_ID) AS SALES_ID,
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    TRIM(PRODUCT_ID) AS PRODUCT_ID,
    TRIM(STORE_ID) AS STORE_ID,
    DATE_KEY,
    QUANTITY,
    ROUND(UNIT_PRICE, 2) AS UNIT_PRICE,
    ROUND(DISCOUNT, 2) AS DISCOUNT,
    ROUND(SALES_AMOUNT, 2) AS SALES_AMOUNT,
    UPPER(TRIM(PAYMENT_METHOD)) AS PAYMENT_METHOD
FROM RETAIL_ANALYTICS_DB.RAW.SALES_RAW
WHERE SALES_ID IS NOT NULL;

SELECT COUNT(*) FROM SALES_STG;

SELECT * FROM SALES_STG LIMIT 10;

SHOW TABLES;

