USE WAREHOUSE RETAIL_WH;
USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA MART;

CREATE OR REPLACE TABLE DIM_CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    GENDER,
    AGE,
    CITY,
    STATE,
    CUSTOMER_SEGMENT,
    JOIN_DATE
FROM RETAIL_ANALYTICS_DB.STAGING.CUSTOMERS_STG;

SELECT * FROM DIM_CUSTOMERS LIMIT 10;
SELECT COUNT(*) FROM DIM_CUSTOMERS;

CREATE OR REPLACE TABLE DIM_PRODUCTS AS
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    SUB_CATEGORY,
    BRAND,
    UNIT_PRICE
FROM RETAIL_ANALYTICS_DB.STAGING.PRODUCTS_STG;

SELECT * FROM DIM_PRODUCTS LIMIT 10;

CREATE OR REPLACE TABLE DIM_STORES AS
SELECT
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    REGION
FROM RETAIL_ANALYTICS_DB.STAGING.STORES_STG;

SELECT * FROM DIM_STORES LIMIT 10;

CREATE OR REPLACE TABLE DIM_DATES AS
SELECT
    DATE_KEY,
    FULL_DATE,
    DAY,
    MONTH,
    MONTH_NAME,
    QUARTER,
    YEAR,
    WEEKDAY,
    WEEK_NUMBER,
    IS_WEEKEND
FROM RETAIL_ANALYTICS_DB.STAGING.DATES_STG;

SELECT * FROM DIM_DATES LIMIT 10;

SHOW TABLES IN SCHEMA MART;

SELECT COUNT(*) FROM DIM_CUSTOMERS;
SELECT COUNT(*) FROM DIM_PRODUCTS;
SELECT COUNT(*) FROM DIM_STORES;
SELECT COUNT(*) FROM DIM_DATES;
SELECT COUNT(*) FROM FACT_SALES;


USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA MART;

DROP TABLE IF EXISTS DIM_CUSTOMER;
DROP TABLE IF EXISTS DIM_PRODUCT;
DROP TABLE IF EXISTS DIM_STORE;
DROP TABLE IF EXISTS DIM_DATE;