USE WAREHOUSE RETAIL_WH;
USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA MART;

CREATE OR REPLACE TABLE FACT_SALES AS
SELECT
    SALES_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    STORE_ID,
    DATE_KEY,
    QUANTITY,
    UNIT_PRICE,
    DISCOUNT,
    SALES_AMOUNT,
    PAYMENT_METHOD
FROM RETAIL_ANALYTICS_DB.STAGING.SALES_STG;

SELECT COUNT(*) FROM FACT_SALES;

SELECT * FROM FACT_SALES LIMIT 10;

SHOW TABLES;

SELECT COUNT(*)
FROM FACT_SALES f
LEFT JOIN DIM_CUSTOMER c
ON f.CUSTOMER_ID = c.CUSTOMER_ID
WHERE c.CUSTOMER_ID IS NULL;


SELECT COUNT(*)
FROM FACT_SALES f
LEFT JOIN DIM_PRODUCT p
ON f.PRODUCT_ID = p.PRODUCT_ID
WHERE p.PRODUCT_ID IS NULL;

SELECT COUNT(*)
FROM FACT_SALES f
LEFT JOIN DIM_STORE s
ON f.STORE_ID = s.STORE_ID
WHERE s.STORE_ID IS NULL;

SELECT COUNT(*)
FROM FACT_SALES f
LEFT JOIN DIM_DATE d
ON f.DATE_KEY = d.DATE_KEY
WHERE d.DATE_KEY IS NULL;