USE WAREHOUSE RETAIL_WH;
USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA REPORTING;


-- Sales Summary

CREATE OR REPLACE VIEW VW_SALES_SUMMARY AS
SELECT
    DATE_KEY,
    COUNT(SALES_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_QUANTITY,
    ROUND(SUM(SALES_AMOUNT),2) AS TOTAL_REVENUE,
    ROUND(AVG(SALES_AMOUNT),2) AS AVG_ORDER_VALUE
FROM RETAIL_ANALYTICS_DB.MART.FACT_SALES
GROUP BY DATE_KEY;

SELECT *
FROM VW_SALES_SUMMARY
LIMIT 10;

-- Product Performance

CREATE OR REPLACE VIEW VW_PRODUCT_PERFORMANCE AS
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.BRAND,

    COUNT(F.SALES_ID) AS TOTAL_ORDERS,

    SUM(F.QUANTITY) AS TOTAL_UNITS_SOLD,

    ROUND(SUM(F.SALES_AMOUNT),2) AS TOTAL_REVENUE

FROM RETAIL_ANALYTICS_DB.MART.FACT_SALES F

JOIN RETAIL_ANALYTICS_DB.MART.DIM_PRODUCTS P
ON F.PRODUCT_ID = P.PRODUCT_ID

GROUP BY
P.PRODUCT_ID,
P.PRODUCT_NAME,
P.CATEGORY,
P.BRAND;

SELECT *
FROM VW_PRODUCT_PERFORMANCE
LIMIT 10;

-- Store Performance

CREATE OR REPLACE VIEW VW_STORE_PERFORMANCE AS
SELECT

S.STORE_ID,
S.STORE_NAME,
S.CITY,
S.STATE,
S.REGION,

COUNT(F.SALES_ID) AS TOTAL_ORDERS,

SUM(F.QUANTITY) AS TOTAL_ITEMS,

ROUND(SUM(F.SALES_AMOUNT),2) AS TOTAL_REVENUE

FROM RETAIL_ANALYTICS_DB.MART.FACT_SALES F

JOIN RETAIL_ANALYTICS_DB.MART.DIM_STORES S
ON F.STORE_ID=S.STORE_ID

GROUP BY

S.STORE_ID,
S.STORE_NAME,
S.CITY,
S.STATE,
S.REGION;

SELECT *
FROM VW_STORE_PERFORMANCE
LIMIT 10;

-- Customer Analytics

CREATE OR REPLACE VIEW VW_CUSTOMER_ANALYTICS AS

SELECT

C.CUSTOMER_ID,
C.FIRST_NAME,
C.LAST_NAME,
C.CUSTOMER_SEGMENT,

COUNT(F.SALES_ID) AS TOTAL_PURCHASES,

SUM(F.QUANTITY) AS ITEMS_PURCHASED,

ROUND(SUM(F.SALES_AMOUNT),2) AS LIFETIME_VALUE

FROM RETAIL_ANALYTICS_DB.MART.FACT_SALES F

JOIN RETAIL_ANALYTICS_DB.MART.DIM_CUSTOMERS C
ON F.CUSTOMER_ID=C.CUSTOMER_ID

GROUP BY

C.CUSTOMER_ID,
C.FIRST_NAME,
C.LAST_NAME,
C.CUSTOMER_SEGMENT;

SELECT *
FROM VW_CUSTOMER_ANALYTICS
LIMIT 10;

-- Monthly Sales

CREATE OR REPLACE VIEW VW_MONTHLY_SALES AS

SELECT

D.YEAR,
D.MONTH,
D.MONTH_NAME,

SUM(F.SALES_AMOUNT) AS TOTAL_REVENUE,

SUM(F.QUANTITY) AS TOTAL_QUANTITY,

COUNT(F.SALES_ID) AS TOTAL_ORDERS

FROM RETAIL_ANALYTICS_DB.MART.FACT_SALES F

JOIN RETAIL_ANALYTICS_DB.MART.DIM_DATES D
ON F.DATE_KEY=D.DATE_KEY

GROUP BY

D.YEAR,
D.MONTH,
D.MONTH_NAME

ORDER BY
D.YEAR,
D.MONTH;

SELECT *
FROM VW_MONTHLY_SALES;

SHOW VIEWS;