USE WAREHOUSE RETAIL_WH;
USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA REPORTING;

-- Duplicate customers
SELECT CUSTOMER_ID, COUNT(*)
FROM STAGING.CUSTOMERS_STG
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1;

-- Missing Product IDs
SELECT *
FROM STAGING.SALES_STG
WHERE PRODUCT_ID IS NULL;

-- Negative Sales Amount
SELECT *
FROM STAGING.SALES_STG
WHERE SALES_AMOUNT < 0;